{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-encryption-key" (include "deckwatch.fullname" .))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deckwatch.fullname" . }}-encryption-key
  labels:
    {{- include "deckwatch.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  encryption-key: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
